Undeploy of solution and bug when creating new role removed.
radon-h2020/tosca-blueprint-aws-lambda pull request #4
Opened 2019-11-12 09:41 UTC by neza-vehovar

2019-11-16 21:06 UTC, cankarm requested changes
The `undeploy` is not correctly implemented - see other comments.

2019-11-16 21:06 UTC, cankarm commented on README.md
> +`opera deploy <some undeploy name> resize_service_opera_undeploy.yml`
I think that we are missing the point here. The `opera` has already the `undeploy` action, see:
```
(.venv) matic@MC-COMP:~/Documents/XLAB/Projects/RADON/03_git/xOpera/opera$ opera
error: the following arguments are required: command
usage: opera [-h] {deploy,undeploy} ...

opera orchestrator

positional arguments:
  {deploy,undeploy}
    deploy           Deploy service template from CSAR
    undeploy         Undeploy service template

optional arguments:
  -h, --help         show this help message and exit
```

Therefore you do not need to make new yaml, Only populate current one with instructions for undeploy/delete. See [here](https://github.com/xlab-si/xopera-opera/blob/master/examples/service.yaml) the `delete` parts.

2019-11-16 21:06 UTC, cankarm commented on playbooks/aws_role/undeploy.yml
> +- hosts: all
Be careful with this whole undeploy block. Can you check with ansible if there is another function/action related with this role?

2019-11-16 21:06 UTC, cankarm commented on playbooks/lambda/create.yml
> +      delay: 6
This is not relevant only for `undeploy` therefore it should be added as a separate pull request.

2019-11-16 21:06 UTC, cankarm commented on resize_service_opera_undeploy.yml
> +        - host: my-workstation
Remove this file. Not needed.

2020-01-23 10:03 UTC, neza-vehovar commented
Changes were done.

2020-01-23 10:06 UTC, cankarm approved these changes

2020-01-23 10:08 UTC, cankarm commented
I tested with xOpera and it successfully removes function and buckets!
LGTM!

2020-01-23 10:08 UTC, merged